---
title: "Analyses of Ensembl VEP purifying selection"
author: "Stephen Rong"
date: "2024-02-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r preamble}
# load libraries
library(tidyverse)
library(data.table)
library(ggthemes)
library(viridis)
library(scales)

# load tables
gnomAD_vep_table_full <- readRDS("../../results/gnomAD_selection_preprocess/gnomAD_vep_table_full.rds")
gnomAD_vep_table_full_category <- readRDS("../../results/gnomAD_selection_preprocess/gnomAD_vep_table_full_category.rds")
```

```{r visualize consq}
ggplot(gnomAD_vep_table_full %>% 
	filter(!is.na(phyloP_mean))) + 
	geom_hline(yintercept = 0, color = "black") + 
	geom_point(aes(x = worst_consq_string, y = phyloP_mean, color = worst_consq_string), position = position_dodge(width = 0)) + 
	geom_errorbar(aes(x = worst_consq_string, ymin = phyloP_lci, ymax = phyloP_uci, color = worst_consq_string), width = 0.5, position = position_dodge(width = 0)) + 
	cowplot::theme_cowplot() + 
	theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1), axis.line.x = element_blank()) + 
	scale_fill_viridis_d() + 
	scale_color_viridis_d() + 
	labs(x = "Ensembl VEP consequence (worst)", y = "Mean constraint (phyloP)", color = "ENCODE cCREs") + 
	guides(color = "none") + 
	theme(aspect.ratio = 1/2)
ggsave("../../results/gnomAD_selection_analysis/gnomAD_vep_table_full_phyloP.pdf")
```

```{r get mean and confidence interval values}
gnomAD_vep_table_full %>% filter(worst_consq_string == "start lost") %>% dplyr::select(worst_consq_string, phyloP_mean, phyloP_lci, phyloP_uci)
gnomAD_vep_table_full %>% filter(worst_consq_string == "splice donor variant") %>% dplyr::select(worst_consq_string, phyloP_mean, phyloP_lci, phyloP_uci)
gnomAD_vep_table_full %>% filter(worst_consq_string == "splice acceptor variant") %>% dplyr::select(worst_consq_string, phyloP_mean, phyloP_lci, phyloP_uci)
gnomAD_vep_table_full %>% filter(worst_consq_string == "missense variant") %>% dplyr::select(worst_consq_string, phyloP_mean, phyloP_lci, phyloP_uci)
gnomAD_vep_table_full %>% filter(worst_consq_string == "stop gained") %>% dplyr::select(worst_consq_string, phyloP_mean, phyloP_lci, phyloP_uci)
```
