---
title: "Analyses of individual promoters in MPAC-satmut_promoters"
author: "Stephen Rong"
date: "2024-04-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r preamble}
# load libraries
library(Cairo)
library(tidyverse)
library(data.table)
library(viridis)
library(ggpubr)
library(patchwork)
library(scales)

satmut_promoters_gene_metadata <- as_tibble(fread("../../results/satmut_promoters_preprocess/satmut_promoters_gene_metadata/satmut_promoters_gene_metadata.txt.gz"))

satmut_promoters_final_prom_all <- as_tibble(fread("../../results/satmut_promoters_preprocess/satmut_promoters_final_prom/satmut_promoters_final_prom_all.txt.gz")) %>% 
  filter(analysis_version == "promoter_250bp")

load_satmut_for_gene <- function(gene) {
  gene_meta <- satmut_promoters_gene_metadata %>% filter((gene_name == gene) | (id == gene) | (ensembl_gene == gene) | (ensembl_tx == gene))
  gene_chr <- gene_tb %>% .$seqnames
  gene_id <- gene_meta %>% .$id
  satmut_promoters_final <- as_tibble(fread(paste0("../../results/satmut_promoters_preprocess/satmut_promoters_final/satmut_promoters_final_", gene_chr, ".txt.gz"))) %>% 
    filter(in_promoter_250bp, !in_all_exon_splice) %>%  # masked
    filter(id == gene_id)
  return(satmut_promoters_final)
}

load_satmut_base_for_gene <- function(gene) {
  gene_meta <- satmut_promoters_gene_metadata %>% filter((gene_name == gene) | (id == gene) | (ensembl_gene == gene) | (ensembl_tx == gene))
  gene_chr <- gene_meta %>% .$seqnames
  gene_id <- gene_meta %>% .$id
  satmut_promoters_final <- as_tibble(fread(paste0("../../results/satmut_promoters_preprocess/satmut_promoters_final_base/satmut_promoters_final_base_", gene_chr, ".txt.gz"))) %>% 
    filter(in_promoter_250bp, !in_all_exon_splice) %>%  # masked
    filter(id == gene_id)
  return(satmut_promoters_final)
}

plot_satmut_for_gene <- function(gene) {
  print(paste0("Loading satmut base for ", gene))
  gene_base_tb <- load_satmut_base_for_gene(gene)
  write_tsv(gene_base_tb, gzfile(paste0("../../results/satmut_promoters_analysis/satmut_promoters_individual_promoters/satmut_promoters_individual_promoters_", gene, ".txt.gz")))
  gene_meta <- satmut_promoters_gene_metadata %>% filter((gene_name == gene) | (id == gene) | (ensembl_gene == gene) | (ensembl_tx == gene))
  gene_chr <- gene_meta %>% .$seqnames
  gene_id <- gene_meta %>% .$id
  
  skew_pos_rho <- filter(satmut_promoters_final_prom_all, id == gene_id) %>% .$correlation_mam241_vs_avgKHS_rho_est_pos
  skew_pos_pval <- filter(satmut_promoters_final_prom_all, id == gene_id) %>% .$correlation_mam241_vs_avgKHS_rho_pval_pos
  skew_neg_rho <- filter(satmut_promoters_final_prom_all, id == gene_id) %>% .$correlation_mam241_vs_avgKHS_rho_est_neg
  skew_neg_pval <- filter(satmut_promoters_final_prom_all, id == gene_id) %>% .$correlation_mam241_vs_avgKHS_rho_pval_neg
  
  print(paste0("Plotting satmut for ", gene))
  
  gene_coord_tss <- ifelse(gene_base_tb[1,]$strand == "+", gene_base_tb[1,]$pos - gene_base_tb[1,]$tss_dist, gene_base_tb[1,]$pos + gene_base_tb[1,]$tss_dist)
  gene_coord_250 <- ifelse(gene_base_tb[1,]$strand == "+", gene_coord_tss - 250, gene_coord_tss + 250)
  gene_coord <- paste0(" (", gene_base_tb$chrom[[1]], ":", gene_coord_tss, "-", gene_coord_250, ")")
  
  dist_plot <- ggplot(gene_base_tb) + 
    geom_point(aes(x = tss_dist, y = avgKHS_skew_pred_base, color = phyloP_mam241_pos_base)) +
    theme_bw() + 
    theme(
      aspect.ratio = 1/3, 
      plot.title = element_text(hjust = 0.5), # Center the title, 
      panel.grid.major.x = element_line(color = "grey95"),   # Remove vertical major grid lines
      panel.grid.minor.x = element_blank(),   # Remove vertical minor grid lines
      panel.grid.major.y = element_line(color = "grey95"), # Customize horizontal grid lines
      panel.grid.minor.y = element_blank(), # Optional: lighter horizontal minor grid lines
    ) + 
   ggtitle(bquote(italic(.(gene)) ~ .(gene_coord))) + # Combine italic and plain text
    scale_colour_gradient2(
      low = "#a6611a",
      mid = "grey90",
      high = "#66c2a5",
      midpoint = 0, 
      limits = c(0, 9)
    ) +
    labs(
      x = "Distance to TSS", 
      y = "Mean allelic skew", 
      color = "max(0, phyloP)"
    ) + 
    ylim(c(-2.1, 2.1)) +
    xlim(c(-250,0))

  print(paste0("Plotting satmut base for ", gene))
  skew_plot <- ggplot(gene_base_tb) + 
    geom_point(aes(x = avgKHS_skew_pred_base, y = phyloP_mam241_pos_base, color = avgKHS_skew_pred_base)) + 
    geom_smooth(aes(x = avgKHS_skew_pred_base, y = phyloP_mam241_pos_base, color = avgKHS_skew_pred_base)) + 
    geom_vline(xintercept = 0, color = "grey50", linewidth = 0.1) + 
    theme_bw() + 
    theme(
      aspect.ratio = 1/3, 
      plot.title = element_text(hjust = 0.5), # Center the title, 
      panel.grid.major.x = element_line(color = "grey95"),   # Remove vertical major grid lines
      panel.grid.minor.x = element_blank(),   # Remove vertical minor grid lines
      panel.grid.major.y = element_line(color = "grey95"), # Customize horizontal grid lines
      panel.grid.minor.y = element_blank()  # Optional: lighter horizontal minor grid lines
    ) + 
    scale_colour_gradient2(
      low = "#fc8d62",
      mid = "grey95",
      high = "#8da0cb",
      midpoint = 0, 
      limits = c(-2.1, 2.1)
    ) +
    labs(
      x = "Mean allelic skew", 
      y = "max(0, phyloP)", 
      color = "Mean allelic skew", 
      shape = "SNV"
    ) +  
    xlim(c(-2.1, 2.1)) + 
    ylim(c(0, 11)) + 
    annotate("text", x = -Inf, y = Inf, label = paste0("ρ = ", signif(skew_neg_rho, 2), ", p = ", signif(skew_neg_pval, 2)), hjust = -0.1, vjust = 1.2, size = 3.5) + 
    annotate("text", x = Inf, y = Inf, label = paste0("ρ = ", signif(skew_pos_rho, 2), ", p = ", signif(skew_pos_pval, 2)), hjust = 1.1, vjust = 1.2, size = 3.5)

  dist_plot / skew_plot
  
  print(paste0("Saving satmut for ", gene))
  ggsave(paste0("../../results/satmut_promoters_analysis/satmut_promoters_individual_promoters/satmut_promoters_individual_promoters_", gene, ".pdf"), scale=0.75, device = cairo_pdf)
}

top_select_genes <- as_tibble(fread("../../results/satmut_promoters_analysis/satmut_promoters_overall_promoters/satmut_promoters_pred_final_prom_level_real_bivariate_pos_neg_top_select_genes.txt"))
top_ordered_genes_pos <- as_tibble(fread("../../results/satmut_promoters_analysis/satmut_promoters_overall_promoters/satmut_promoters_pred_final_prom_level_real_bivariate_pos_neg_top_genes_pos.txt"))

for (gene in c("LDLR", top_select_genes$gene_name, top_ordered_genes_pos$gene_name)) {
  plot_satmut_for_gene(gene)
}
```
