---
title: "Analyses of meta-promoters by tss distance in MPAC-satmut_promoters"
author: "Stephen Rong"
date: "2024-04-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r preamble}
# load libraries
library(tidyverse)
library(data.table)
library(viridis)
library(patchwork)
library(corrplot)
library(GGally)

# load tables
satmut_promoters_final_dist_all <- as_tibble(fread("../../results/satmut_promoters_preprocess/satmut_promoters_final_dist/satmut_promoters_final_dist_all.txt.gz")) %>% 
	filter(in_promoter_250bp)

p_fimo_scan <- readRDS("../../results/satmut_promoters_analysis/satmut_promoters_meme_analysis/satmut_promoters_final_fimo_scan_coverage.rds")
p_fimo_scan + theme(aspect.ratio = 1/5) + 
  geom_vline(xintercept = -26, linetype="dashed", color="grey50") + 
	geom_vline(xintercept = -42, linetype="dashed", color="grey50")
ggsave("../../results/satmut_promoters_analysis/satmut_promoters_overall_dist/satmut_promoters_final_fimo_scan_coverage_plot.pdf")
```

```{r meta promoters}
p_phyloP <- ggplot(satmut_promoters_final_dist_all) + 
	geom_line(aes(x = tss_dist, y = phyloP_mam241_dist), color = "black") + 
	geom_vline(xintercept = -26, linetype="dashed", color="grey50") + 
	geom_vline(xintercept = -42, linetype="dashed", color="grey50") + 
	theme_classic() + 
	labs(x = "Distance to TSS", y = "Mean phyloP", color = "Cell line")
p_phyloP
ggsave("../../results/satmut_promoters_analysis/satmut_promoters_overall_dist/satmut_promoters_final_dist_all_phyloP.pdf")

p_ref_pred <- ggplot(satmut_promoters_final_dist_all) + 
	geom_line(aes(x = tss_dist, y = K562_ref_pred_dist, color = "K562")) + 
	geom_line(aes(x = tss_dist, y = HepG2_ref_pred_dist, color = "HepG2")) + 
	geom_line(aes(x = tss_dist, y = SKNSH_ref_pred_dist, color = "SKNSH")) + 
	geom_vline(xintercept = -26, linetype="dashed", color="grey50") + 
	geom_vline(xintercept = -42, linetype="dashed", color="grey50") + 
	theme_classic() + 
	scale_color_manual(values = c("K562" = "#00A79D", "HepG2" = "#FBB040", "SKNSH" = "#ED1C24")) + 
	labs(x = "Distance to TSS", y = "Mean activity", color = "Cell line")
p_ref_pred
ggsave("../../results/satmut_promoters_analysis/satmut_promoters_overall_dist/satmut_promoters_final_dist_all_ref_pred.pdf")

p_skew_pred <- ggplot(satmut_promoters_final_dist_all) + 
	geom_line(aes(x = tss_dist, y = K562_skew_pred_dist, color = "K562")) + 
	geom_line(aes(x = tss_dist, y = HepG2_skew_pred_dist, color = "HepG2")) + 
	geom_line(aes(x = tss_dist, y = SKNSH_skew_pred_dist, color = "SKNSH")) + 
	geom_vline(xintercept = -26, linetype="dashed", color="grey50") + 
	geom_vline(xintercept = -42, linetype="dashed", color="grey50") + 
	theme_classic() + 
	scale_color_manual(values = c("K562" = "#00A79D", "HepG2" = "#FBB040", "SKNSH" = "#ED1C24")) + 
	labs(x = "Distance to TSS", y = "Mean allelic skew", color = "Cell line")
p_skew_pred
ggsave("../../results/satmut_promoters_analysis/satmut_promoters_overall_dist/satmut_promoters_final_dist_all_skew_pred.pdf")

p_phyloP / p_skew_pred / (p_ref_pred + guides(color = "none"))
ggsave("../../results/satmut_promoters_analysis/satmut_promoters_overall_dist/satmut_promoters_final_dist_all_combined_v1.pdf")
```
